--- pyproject.toml.orig	2024-10-25 00:43:39 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [project]
-name = "Werkzeug"
+name = "werkzeug"
 version = "3.0.5"
 description = "The comprehensive WSGI web application library."
 readme = "README.md"
