--- pyproject.toml.orig	2025-08-01 16:02:21 UTC
+++ pyproject.toml
@@ -4,7 +4,7 @@ authors = [{ name = "Toby Mao", email = "toby.mao@gmai
 description = "An easily customizable SQL parser and transpiler"
 readme = "README.md"
 authors = [{ name = "Toby Mao", email = "toby.mao@gmail.com" }]
-license-files = ["LICENSE"]
+license = { file = "LICENSE" }
 requires-python = ">= 3.9"
 classifiers = [
     "Development Status :: 5 - Production/Stable",
