--- pyproject.toml.orig	2022-12-29 14:10:46 UTC
+++ pyproject.toml
@@ -16,7 +16,7 @@ classifiers = [
 python = "^3.7"
 poetry = "^1.2"
 tomlkit = "^0.11.4"
-packaging = "^21.3"
+packaging = ">=21.3"
 
 [tool.poetry.group.dev.dependencies]
 pytest = "^7.0"
