--- pyproject.toml.orig	2022-11-08 19:14:48 UTC
+++ pyproject.toml
@@ -43,7 +43,7 @@ python = "^3.7"
 redis = "<4.5"
 sortedcontainers = "^2.4.0"
 lupa = { version = "^1.13", optional = true }
-aioredis = { version = "^2.0.1", optional = true }
+aioredis = { version = ">=1.3.1,<3.0.0", optional = true }
 
 [tool.poetry.extras]
 lua = ["lupa"]
@@ -74,4 +74,4 @@ markers = [
     "max_server",
     "decode_responses",
 ]
-asyncio_mode="strict"
\ No newline at end of file
+asyncio_mode="strict"
