PORTNAME=	libdispatch
DISTVERSIONPREFIX=	swift-
DISTVERSION=	5.5
DISTVERSIONSUFFIX=	-RELEASE
PORTEPOCH=	1
CATEGORIES=	devel

MAINTAINER=	fluffy@FreeBSD.org
COMMENT=	Grand Central Dispatch API support library

LICENSE=	APACHE20

USES=		cmake compiler:c++17-lang
USE_LDCONFIG=	yes

USE_GITHUB=	yes
GH_ACCOUNT=	apple
GH_PROJECT=	swift-corelibs-libdispatch

.include <bsd.port.mk>
