--- pyproject.toml.orig	2024-03-04 21:54:28 UTC
+++ pyproject.toml
@@ -40,7 +40,7 @@ dependencies = [
     "Topic :: Utilities",
 ]
 dependencies = [
-    "awkward_cpp==30",
+    "awkward_cpp==31",
     "importlib_metadata>=4.13.0;python_version < \"3.12\"",
     "numpy>=1.18.0",
     "packaging",
