--- zellij-utils/Cargo.toml.orig	2024-11-04 10:57:41 UTC
+++ zellij-utils/Cargo.toml
@@ -56,7 +56,7 @@ futures = "0.3.28"
 notify-debouncer-full = "0.1.0"
 humantime = "2.1.0"
 futures = "0.3.28"
-openssl-sys = { version = "0.9.93", features = ["vendored"] }
+openssl-sys = { version = "0.9.93" }
 isahc = "1.7.2"
 curl-sys = { version = "0.4", features = ["force-system-lib-on-osx"] }
 
