--- binder/environment.yml.orig	2023-01-18 21:16:10 UTC
+++ binder/environment.yml
@@ -31,10 +31,10 @@ dependencies:
 - pyqt <5.16
 - pyqtwebengine <5.16
 - python-lsp-black >=1.2.0
-- python-lsp-server >=1.7.1,<1.8.0
+- python-lsp-server >0
 - pyxdg >=0.26
 - pyzmq >=22.1.0
-- qdarkstyle >=3.0.2,<3.1.0
+- qdarkstyle >=3.0.2
 - qstylizer >=0.2.2
 - qtawesome >=1.2.1
 - qtconsole >=5.4.0,<5.5.0
