--- binder/environment.yml.orig	2022-10-14 18:00:34 UTC
+++ binder/environment.yml
@@ -33,7 +33,7 @@ dependencies:
 - python-lsp-server >=1.5.0,<1.6.0
 - pyxdg >=0.26
 - pyzmq >=22.1.0
-- qdarkstyle >=3.0.2,<3.1.0
+- qdarkstyle >=3.0.2
 - qstylizer >=0.1.10
 - qtawesome >=1.0.2
 - qtconsole >=5.3.2,<5.4.0
