--- pyproject.toml.orig	2025-07-17 21:33:41 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["setuptools>=68.2.0"]
+requires = ["setuptools>=61"]
 build-backend = "setuptools.build_meta"
 
 [project]
@@ -31,7 +31,7 @@ dependencies = [
 dependencies = [
     "aiohttp >= 3.9.2, < 4.0.0",
     "aioitertools >= 0.5.1, < 1.0.0",
-    "botocore >= 1.38.40, < 1.38.47", # NOTE: When updating, always keep `project.optional-dependencies` aligned
+    "botocore >= 1.38.40", # NOTE: When updating, always keep `project.optional-dependencies` aligned
     "python-dateutil >= 2.1, < 3.0.0",
     "jmespath >= 0.7.1, < 2.0.0",
     "multidict >= 6.0.0, < 7.0.0",
@@ -40,10 +40,10 @@ awscli = [
 
 [project.optional-dependencies]
 awscli = [
-    "awscli >= 1.40.39, < 1.40.46",
+    "awscli >= 1.29.81",
 ]
 boto3 = [
-    "boto3 >= 1.38.40, < 1.38.47",
+    "boto3 >= 1.38.40",
 ]
 httpx = [
     "httpx >= 0.25.1, < 0.29"
