Obtained from:	https://github.com/pydantic/pydantic/commit/0660024d616c7559e194847b5e79eee688db9dd8

--- pyproject.toml.orig	2020-02-02 00:00:00 UTC
+++ pyproject.toml
@@ -61,7 +61,7 @@ requires-python = '>=3.7'
 dependencies = [
     'typing-extensions>=4.6.1',
     'annotated-types>=0.4.0',
-    "pydantic-core==2.10.1",
+    "pydantic-core==2.11.0",
 ]
 dynamic = ['version', 'readme']
 
