--- pyproject.toml.orig	2020-02-02 00:00:00 UTC
+++ pyproject.toml
@@ -66,7 +66,7 @@ requires-python = '>=3.7'
 dependencies = [
     'typing-extensions>=4.6.1',
     'annotated-types>=0.4.0',
-    "pydantic-core==2.14.5",
+    "pydantic-core>=2.14.5, <=2.14.6",
     "importlib_metadata; python_version=='3.7'",
 ]
 dynamic = ['version', 'readme']
