--- pyproject.toml.orig	2023-01-16 02:01:00 UTC
+++ pyproject.toml
@@ -1,11 +1,7 @@
 [build-system]
 requires = [
-    "black",
-    "isort",
-    "pyproject-flake8",
     "setuptools>=61.0.0",
     "versioneer[toml]",
-
 ]
 build-backend = "setuptools.build_meta"
 
