--- pyproject.toml.orig	2023-12-13 09:29:50 UTC
+++ pyproject.toml
@@ -4,12 +4,13 @@ source = "scm"
 source = "scm"
 
 [project]
-dynamic = ["version"]
+dynamic = []
 
 name = "amaranth"
 description = "Amaranth hardware definition language"
 authors = [{name = "Amaranth HDL contributors"}]
 license = {file = "LICENSE.txt"}
+version = "%%VERSION%%"
 
 requires-python = "~=3.8"
 dependencies = [
