--- tests/Cargo.toml.orig	2023-04-26 10:25:40 UTC
+++ tests/Cargo.toml
@@ -10,7 +10,7 @@ elsa = "1.7"
 typst-library = { path = "../library" }
 comemo = "0.2"
 elsa = "1.7"
-iai = { git = "https://github.com/reknih/iai" }
+iai = "0.1.1"
 once_cell = "1"
 tiny-skia = "0.6.2"
 ttf-parser = "0.17"
