--- pyproject.toml.orig	2023-05-23 00:26:07 UTC
+++ pyproject.toml
@@ -30,7 +30,7 @@ dependencies = [
     "CacheControl[filecache] >= 0.12.0",
     # NOTE(ww): Release 2.5.0 is broken, subsequent 2.5.x releases fix it.
     # See: https://github.com/CycloneDX/cyclonedx-python-lib/issues/245
-    "cyclonedx-python-lib ~= 2.0, != 2.5.0",
+    "cyclonedx-python-lib >= 2.0, != 2.5.0",
     "html5lib>=1.1",
     "packaging>=23.0.0",                     # https://github.com/pypa/pip-audit/issues/464
     "pip-api>=0.0.28",
