--- pyproject.toml.orig	2024-11-01 10:44:56 UTC
+++ pyproject.toml
@@ -22,8 +22,7 @@ dependencies = [
 ]
 
 dependencies = [
-   "protobuf>=3.7.0, <4",
-   "importlib_resources",  # Needed for 3.9 and below
+   "protobuf>=3.7.0",
 ]
 
 [project.optional-dependencies]
