--- pyproject.toml.orig	2023-08-27 15:24:16 UTC
+++ pyproject.toml
@@ -52,9 +52,9 @@ keywords = [
 [tool.poetry.dependencies]
 # ATTENTION: keep `deps.lowest.r` file in sync
 python = "^3.7"
-packageurl-python = ">= 0.11"
-py-serializable = "^0.11.1"
-sortedcontainers = "^2.4.0"
+packageurl-python = ">= 0.9"
+py-serializable = ">= 0.11.1"
+sortedcontainers = "^2.3.0"
 
 [tool.poetry.dev-dependencies]
 ddt = "^1.6.0"
