--- pyproject.toml.orig	2024-02-27 20:49:34 UTC
+++ pyproject.toml
@@ -21,7 +21,6 @@ dependencies = [
 dependencies = [
   "asdf-standard>=1.0.1",
   "asdf-transform-schemas>=0.3",
-  "asdf-unit-schemas>=0.1",
   "importlib-metadata>=4.11.4",
   "jmespath>=0.6.2",
   "numpy>=1.22",
