--- codex-rs/rmcp-client/Cargo.toml.orig	2025-10-31 00:56:28 UTC
+++ codex-rs/rmcp-client/Cargo.toml
@@ -19,8 +19,9 @@ keyring = { workspace = true, features = [
 keyring = { workspace = true, features = [
     "apple-native",
     "crypto-rust",
-    "linux-native-async-persistent",
+    "linux-native",
     "windows-native",
+    "async-secret-service",
 ] }
 mcp-types = { path = "../mcp-types" }
 oauth2 = "5"
