--- codex-rs/keyring-store/Cargo.toml.orig	2025-10-31 00:56:28 UTC
+++ codex-rs/keyring-store/Cargo.toml
@@ -10,7 +10,8 @@ keyring = { workspace = true, features = [
 keyring = { workspace = true, features = [
     "apple-native",
     "crypto-rust",
-    "linux-native-async-persistent",
+    "linux-native",
     "windows-native",
+    "async-secret-service",
 ] }
 tracing = { workspace = true }
