--- pyproject.toml.orig	2024-03-12 10:46:29 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["setuptools>=62.6", "versioneer[toml]==0.28"]
+requires = ["setuptools>=62.6", "versioneer[toml]>=0.28"]
 build-backend = "setuptools.build_meta"
 
 [project]
@@ -26,7 +26,6 @@ dependencies = [
 readme = "README.md"
 requires-python = ">=3.9"
 dependencies = [
-    "dask == 2024.3.0",
     "pyarrow>=7.0.0",
     "pandas >= 2",
 ]
